name: yskc
description: 元氏卡车.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  pull_to_refresh: 1.6.3
  connectivity: ^2.0.2
  giffy_dialog: ^1.8.0
  azlistview: ^1.1.0
  common_utils: ^1.2.1
  event_bus: ^1.1.1
  input_calculator: ^1.1.0+5
  expressions: ^0.1.5
  flutter_grid_button: ^1.1.7
  auto_size_text: ^2.1.0
  camera: ^0.5.8+8
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  fl_chart: ^0.11.1
  fluttertoast: ^7.1.1
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  provider: ^4.3.2+2
  json_annotation: ^3.1.1
  flutter_picker: ^1.1.5
  intl: ^0.16.1
  retrofit: ^1.3.4+1
  cupertino_icons: ^1.0.0
dev_dependencies:
  retrofit_generator: ^1.4.0+2
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.1
  json_serializable: ^3.5.0
flutter:
  uses-material-design: true
